Mxonline/urls.py
# -*- coding:utf-8 -*-
"""Mxonline URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
import xadmin
from django.conf.urls import url, include
from django.views.static import serve

from Mxonline.settings import MEDIA_ROOT, STATIC_ROOT
from apps.users.views import LoginView, RegisterView, ActiveUserView, ForgetPwdView
from apps.users.views import ResetView, ModifyPwdView, LogoutView, IndexView

urlpatterns = [

    url(r'^xadmin/', xadmin.site.urls),
    url('^$',IndexView.as_view(),name='index'),
    url('^login/$',LoginView.as_view(),name="login"),
    url('^logout/$',LogoutView.as_view(),name="logout"),
    url('^register/$', RegisterView.as_view(), name="register"),
    url('^captcha/', include('captcha.urls')),
    url('^active/(?P<active_code>.*)/$',ActiveUserView.as_view(),name="user_active"),
    url('^forget/$',ForgetPwdView.as_view(),name="forget_pwd"),
    url('^reset/(?P<active_code>.*)/$',ResetView.as_view(),name="reset_pwd"),
    url('^modify_pwd/$',ModifyPwdView.as_view(),name="modify_pwd"),

    #课程机构url配置
    url('^org/', include('apps.organization.urls', namespace='org')),

    #课程相关url配置
    url('^course/', include('apps.courses.urls', namespace='course')),

    #配置上传文件的访问处理函数
    url('^media/(?P<path>.*)$', serve,{"document_root":MEDIA_ROOT}),

    #自定义代理服务
    url('^static/(?P<path>.*)$', serve,{"document_root":STATIC_ROOT}),

    # 课程相关url配置
    url('^users/', include('apps.users.urls', namespace='users')),

]



# 全局404页面
handler404 = 'apps.users.views.page_not_found'

#全局505页面
handler505 = 'apps.users.views.page_error'

apps/courses/urls.py
#-*-coding:utf-8-*-



from django.conf.urls import url,include

from .views import CourseListView,CourseDetaiView,CourseInfoView,CommentsView,AddCommentsView,VideoPlayView

urlpatterns = [
    #课程列表页
    url('^list/$',CourseListView.as_view(), name='course_list'),

    #课程详情页
    url('^detail/(?P<course_id>\d+)/$',CourseDetaiView.as_view(), name='course_detail'),

    # 课程信息视频页
    url('^info/(?P<course_id>\d+)/$', CourseInfoView.as_view(), name='course_info'),

    # 课程信息视频页
    url('^comment/(?P<course_id>\d+)/$', CommentsView.as_view(), name='course_comment'),

    # 添加课程评论
    url('^add_comment/$', AddCommentsView.as_view(), name='add_comment'),#course_id不需要写，因为做post操作已经携带

    # 课程视频播放页
    url('^video/(?P<video_id>\d+)/$', VideoPlayView.as_view(), name='video_play'),
]

apps/organization/urls.py
#-*-coding:utf-8-*-
__author__ = 'kerberos'
__date__ = '2017/10/29 14:58 '


from django.conf.urls import url

from .views import OrgView,AddUserAskView,OrgHomeView,OrgCourseView,OrgDescView,OrgTeacherView,AddFavView
from .views import TeacherListView,TeacherDetailView

urlpatterns = [
    # 课程机构列表页
    url('^list/$', OrgView.as_view(), name="org_list"),
    url('^add_ask/$',AddUserAskView.as_view(), name='add_ask'),
    url('^home/(?P<org_id>\d+)$',OrgHomeView.as_view(),name="org_home"),
    url('^course/(?P<org_id>\d+)$', OrgCourseView.as_view(), name="org_course"),
    url('^desc/(?P<org_id>\d+)$', OrgDescView.as_view(), name="org_desc"),
    url('^org_teacher/(?P<org_id>\d+)$', OrgTeacherView.as_view(), name="org_teacher"),

    #机构收藏
    url('^add_fav/$',AddFavView.as_view(), name='add_fav'),

    #教师列表页
    url('^teacher/list/$',TeacherListView .as_view(), name='teacher_list'),

    #j讲师详情页
    url('^teacher/detail/(?P<teacher_id>\d+)$', TeacherDetailView.as_view(), name="teacher_detail"),
]

apps/users/urls.py
#-*-coding:utf-8-*-

from django.conf.urls import url

from .views import UserInfoView, UploadImageView, UpdatePwdView, SendEmailCodeView
from .views import UpdateEmailView, MyCourseView, MyFavOrgView, MyFavTeacherView, MyFavCourseView, MyMessageView

urlpatterns = [
    #用户信息
    url('^info/$',UserInfoView.as_view(), name='user_info'),

    #用户头像上传
    url('^image/upload/$',UploadImageView.as_view(), name='image_upload'),

    # 用户个人中心修改密码
    url('^update/pwd/$', UpdatePwdView.as_view(), name='update_pwd'),

    # 发送邮箱验证码
    url('^sendemail_code/$', SendEmailCodeView.as_view(), name='sendemail_code'),

    # 修改邮箱
    url('^update_email/$', UpdateEmailView.as_view(), name='update_email'),

    #我的课程
    url('^mycourse/$', MyCourseView.as_view(), name='mycourse'),

    # 我的收藏课程机构
    url('^myfav/org/$', MyFavOrgView.as_view(), name='myfav_org'),

    # 我的收藏授课讲师
    url('^myfav/teacher/$', MyFavTeacherView.as_view(), name='myfav_teacher'),

    # 我的收藏课程
    url('^myfav/course/$', MyFavCourseView.as_view(), name='myfav_course'),

    # 我的消息
    url('^mymessage/$', MyMessageView.as_view(), name='mymessage'),
]

apps/courses/models.py
#-*-coding:utf-8-*-

from django.db import models
from apps.organization.models import CourseOrg,Teacher

from datetime import datetime
# Create your models here.


class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg,verbose_name="课程机构",null=True,blank=True)
    name = models.CharField(max_length=50,verbose_name="课程名")
    desc = models.CharField(max_length=300,verbose_name="课程描述")
    detail = models.TextField(verbose_name="课程详情")
    is_banner = models.BooleanField(default=False, verbose_name="是否轮播")
    teacher = models.ForeignKey(Teacher,verbose_name="讲师",null=True,blank=True)
    degree = models.CharField(verbose_name='难度',choices=(("cj","初级"),("zj","中级"),("gj","高级")),max_length=2)
    learn_times = models.IntegerField(default=0,verbose_name="学习时长(分钟数)")
    students = models.IntegerField(default=0,verbose_name="学习人数")
    fav_num = models.IntegerField(default=0,verbose_name="收藏")
    image = models.ImageField(upload_to="course/%Y/m",verbose_name="封面图",max_length=100)
    click_nums = models.IntegerField(default=0, verbose_name="点击量")
    category = models.CharField(default="后端开发",max_length=20,verbose_name="课程类别")
    tag = models.CharField(default='', verbose_name="课程标签",max_length=16)
    youneed_know = models.CharField(max_length=500, default="", verbose_name="课程须知")
    teacher_tell = models.CharField(max_length=500, default="", verbose_name="老师告诉你")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")


    class Meta:
        verbose_name = "课程"
        verbose_name_plural = verbose_name


    def get_zj_nums(self):
        #获取课程章节数
        return self.lesson_set.all().count()
    get_zj_nums.short_description = "章节数"


    def go_to(self):
        from django.utils.safestring import mark_safe
        return mark_safe("<a href='http://www.google.com'>跳转</a>")
    go_to.short_description = "跳转"

    def get_learn_users(self):
        return self.usercourse_set.all()[:5]

    def get_course_lesson(self):
        #获取课程章节
        return self.lesson_set.all()


    def __str__(self):
        return self.name


class BannerCourse(Course):
    class Meta:
        verbose_name = '轮播课程'
        verbose_name_plural = verbose_name
        proxy = True


class Lesson(models.Model):
    course = models.ForeignKey(Course,verbose_name="课程")
    name = models.CharField(max_length=100,verbose_name="章节名")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    class Meta:
        verbose_name  = "章节"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


    def get_leson_video(self):
        #获取章节视频
        return  self.video_set.all()

class Video(models.Model):
    lesson = models.ForeignKey(Lesson,verbose_name="章节")
    name = models.CharField(max_length=100,verbose_name="视频名")
    learn_times = models.IntegerField(default=0,verbose_name="学习时长(分钟数)")
    url = models.CharField(max_length=200,default="",verbose_name="访问地址")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    class Meta:
        verbose_name  = "视频"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

class CourseResource(models.Model):
    course = models.ForeignKey(Course,verbose_name="课程")
    name = models.CharField(max_length=100,verbose_name="名称")
    download = models.FileField(upload_to="course/resource/%Y%m",verbose_name="资源文件",max_length=100)      #文件类型字段
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    class Meta:
        verbose_name  = "课程资源"
        verbose_name_plural = verbose_name

templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}在线网络学习平台{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    {% block custom_css %} {% endblock %}

    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

</head>


<body>
<section class="headerwrap ">
    <header>
		<div  class=" header">
 			<div class="top">
				<div class="wp">
					<!--登录后跳转-->
                        {% if request.user.is_authenticated %}
                                    <div class="personal">
                                      <dl class="user fr">
                                        <dd>{{ user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                        <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                                      </dl>
                                      <div class="userdetail">
                                        <dl>
                                          <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}" /></dt>
                                          <dd>
                                            <h2>{{ request.user.nick_name }}</h2>
                                            <p>{{ request.user.username }}</p>
                                          </dd>
                                        </dl>
                                        <div class="btn">
                                          <a class="personcenter fl" href="{% url 'users:user_info' %}">个人中心</a>
                                          <a class="fr" href="{% url 'logout' %}">退出</a>
                                        </div>
                                      </div>
                                    </div>
                                    <a href="{% url 'users:mymessage' %}">
                                      <div class="msg-num">
                                        <span id="MsgNum">{{ request.user.unread_nums }}</span>
                                      </div>
                                    </a>
                                  {% else %}
                                    <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                                    <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                                  {% endif %}
                                </div>
                              </div>

            <div class="middle">
                <div class="wp">
                    <a href="{% url 'index' %}"><img class="fl" src="{% static 'images/head.jpg' %}"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课老师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
                    </div>
                </div>
            </div>


			<nav>
				<div class="nav">
					<div class="wp">
						<ul>
							<li class="{% ifequal request.path '/' %}active{% endifequal %}"><a href="{% url 'index' %}">首页</a></li>
							<li class="{% ifequal request.path|slice:'7' '/course' %}active{% endifequal %}">
								<a href="{% url 'course:course_list' %}">
									公开课<img class="hot" src="{% static 'images/nav_hot.png' %}">
								</a>
							</li>
							<li class="{% ifequal request.path|slice:'12' '/org/teacher' %}active{% endifequal %}">
								<a href="{% url 'org:teacher_list' %}">授课教师</a>
							</li>
							<li class="{% ifequal request.path|slice:'9' '/org/list' %}active{% endifequal %}" ><a href="{% url 'org:org_list' %}">授课机构</a></li>
						</ul>
					</div>
				</div>
			</nav>

			</div>
    </header>
</section>
<!--crumbs start-->
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li>课程机构</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block content %}

{% endblock %}
<footer>
		<div class="footer">
			<div class="wp">
				<ul class="cont">
					<li class="logo"><td width="80">平台支持:&nbsp;&nbsp;</td><a href="http://s1.ananas.chaoxing.com/mooc/android/fanya_2.8.1(2016-08-31).apk"><img src="{% static 'images/android.png' %}"/></a></li>
					<li class="code"><img src="{% static 'images/code.png' %}"/><p class="center">扫描关注微信</p></li>
					<li class="third"><img class="fl" src="{% static 'images/tell.png' %}"/><p class="tell">13012345678</p><p class="time">周一至周日 9:00-18:00</p></li>
				</ul>

			</div>
			<p class="line"></p>
			<div class="wp clear">
                <span class="fl">Copyright 2013-2017 北京慕华信息科技有限公司</span>
                <span class="fr">京ICP证140571号 | 京公网安备 11010802017721广播电视节目制作经营许可证（京）字第05791号</span>
			</div>
		</div>

	</footer>

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}"  type="text/javascript"></script>

{% block custom_js %}{% endblock %}

</body>
</html>

templates/org_base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}机构首页{% endblock  %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">

    {% block custom_css %}{% endblock %}

    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

    {% block custom_js %}{% endblock %}

</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
		<div  class="header2 header">

              {% if request.user.is_authenticated %}
                   <div class="top">
				<div class="wp">
                 {% if request.user.is_authenticated %}
                                <div class="personal">
                                  <dl class="user fr">
                                    <dd>{{ user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                    <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                                  </dl>
                                  <div class="userdetail">
                                    <dl>
                                      <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}" /></dt>
                                      <dd>
                                        <h2>{{ request.user.nick_name }}</h2>
                                        <p>{{ request.user.username }}</p>
                                      </dd>
                                    </dl>
                                    <div class="btn">
                                      <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
                                      <a class="fr" href="{% url 'logout' %}">退出</a>
                                    </div>
                                  </div>
                                </div>
                                <a href="{% url 'users:mymessage' %}">
                                  <div class="msg-num">
                                    <span id="MsgNum">{{ request.user.unread_nums }}</span>
                                  </div>
                                </a>
                              {% else %}
                                <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                                <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                              {% endif %}
                     </div>
                   </div>
                    {% else %}
                         <div class="top">

				            <div class="wp">
					    <div class="fl">
                        <p>服务电话：<b>13231313131</b></p></div>
					<!--登录后跳转-->
                        <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                              </div>
                        </div>

                {% endif %}


    <div class="middle companyheader">
        <div class="wp">
            <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
            <div class="head fl">
                <h1>
                    慕课网
                    <img src="{% static 'images/authentication.png' %}"/>
                    <img src="{% static 'images/gold.png' %}"/>
                </h1>
                <p class="fl">
                    <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                    <span class="precision company-credit" data-star-scope="5.0"></span>
                    <span class="key">5.0</span>
                </p>
            </div>
            <div class="btn fr collectionbtn  notlogin
                 "data-favid="22" data-fav-type="1">
                 {% if has_fav %}已收藏{% else %}收藏{% endif %}
            </div>

        </div>
    </div>
			</div>
    </header>
</section>
<section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
			<li><a href="{% url "org:org_list" %}">课程机构</a>></li>
			<li>{% block page_path %}机构首页{% endblock %}</li>
		</ul>
	</div>
</section>

<section>
	<div class="wp list personal_list comp">
		<div class="left">
			<ul>
				<li class="{% ifequal current_page 'home' %}active2{% endifequal %}"><a href="{% url 'org:org_home' course_org.id %}">机构首页</a></li>
                <li class="{% ifequal current_page 'course' %}active2{% endifequal %}"><a href="{% url 'org:org_course' course_org.id %}">机构课程</a></li>
                <li class="{% ifequal current_page 'desc' %}active2{% endifequal %}"><a href="{% url 'org:org_desc' course_org.id %}">机构介绍</a></li>
                <li class="{% ifequal current_page 'teacher' %}active2{% endifequal %}"><a href="{% url 'org:org_teacher' course_org.id %}">机构讲师</a></li>
			</ul>
		</div>

    {% block right_form %}

    {% endblock %}
</section>
<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->
<!--header start-->
</div>
<!--弹出省省市-->
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>

<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
<script type="text/javascript">
    //收藏分享
//收藏分享7-12
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"{% url 'org:add_fav' %}",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
{#            此处只是将csrf_token的值传进去 不能使用{% csrf_token %}是生成一段html代码#}
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="{% url 'login' %}";
                }else{
                    alert(data.msg)
                }
            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}
$('.collectionbtn').on('click', function(){
    add_fav($(this), {{ course_org.id }}, 2);
});
$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path		: '{% static 'images/' %}',
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg  : '暂时还未获得评价！',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);
    $('.jsFavBtn').on('click', function(){
        var type = $(this).attr('data-fav-type');
        if(type == '1'){
            favPraise($(this), 'fav' ,1 , '收藏');
        }else if(type == '3'){
            favPraise($(this), 'fav' ,3 );
        }else if(type == '11'){
            favPraise($(this), 'pra', 1);
        }else if(type == '4'){
            favPraise($(this), 'fav' ,4 );
        }
    });
})
</script>


<script type="text/javascript">
$(function() {
    $('.recordbtn1').click(function(){
        $('.recordbox1').show();
    });
    $('.recordbtn2').click(function(){
        $('.recordbox2').show();
    });
    $('.imgslide').unslider({
        speed: 500,               //  The speed to animate each slide (in milliseconds)
        delay: 3000,              //  The delay between slide animations (in milliseconds)
        complete: function() {},  //  A function that gets called after every slide animation
        keys: true,               //  Enable keyboard (left, right) arrow shortcuts
        dots: true,               //  Display dot navigation
        fluid: false              //  Support responsive design. May break non-responsive designs
    });
    var unslider = $('.imgslide').unslider();
    $('.unslider-arrow').click(function() {
        var fn = this.className.split(' ')[1];
        unslider.data('unslider')[fn]();
    });
});
</script>

</body>
</html>

templates/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title>密码修改</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/animate.css">
	<link rel="stylesheet" type="text/css" href="/static/css/style.css">

<body>
<div class="wp">
    <div class="resetpassword" id="resetPwdForm">
        <h1>修改密码</h1>
        <p>已经通过验证，请设置新密码</p>
        <form id="reset_password_form" action="{% url 'modify_pwd' %}" method="post">
            <ul>
                <li>
                    <span class="">新 密 码 ：</span>
                    <input type="password" name="password1" id="pwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                    <input type="hidden" name="email" value="{{ email }}">
                <li>
                    <span class="">确定密码：</span>
                    <input type="password" name="password2" id="repwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <li class="button">
                    <input type="submit" value="提交">
                </li>
            </ul>
            {% csrf_token %}
        </form>
    </div>
    <div class="resetpassword" id="reset_password_tips" style="display:none;">
        <h1>修改密码成功,请重新登录</h1>
        <img class="fl" src="/static/images/check2.png">
        <p class="successword">已经成功修改密码，请重新登录</p>
    </div>
</div>
</body>
</html>

templates/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}
{% block title %}我的收藏- 在线IT学习平台{% endblock %}
{% load  staticfiles %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="/user/home/">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                        <ul class="tab_header messagehead">
                        <li><a href="{% url 'users:myfav_org' %}">课程机构</a> </li>
                        <li ><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for fav_course in course_list %}
                            <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' fav_course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ fav_course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:course_detail' fav_course.id %}"><h2>{{ fav_course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ fav_course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ fav_course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ fav_course.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ fav_course.id }}"></span>
                            </div>
                        </div>
                        {% endfor %}



                    </div>
                </div>
            </div>
        </div>
{% endblock %}